name: Tests

on:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      #--------------------------------------------------------------------
      # CHECK OUT CODE
      #--------------------------------------------------------------------
      - name: Check out code
        uses: actions/checkout@v4.0.0
      #--------------------------------------------------------------------
      # INSTALL PYTHON
      #--------------------------------------------------------------------
      - name: Set up Python
        uses: actions/setup-python@v4.7.0
        with:
          python-version: 3.11
      #--------------------------------------------------------------------
      # INSTALL PYTHON DEPENDENCIES
      #--------------------------------------------------------------------
      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build
      #--------------------------------------------------------------------
      # BUILD PACKAGE
      #--------------------------------------------------------------------
      - name: Build package
        run: python -m build --sdist --wheel . --outdir dist/